### ISSUE TITLE
TypeError: 'QSpinBox' object is not callable

### ISSUE THREAD

**Issue by Igor4er** [XSden4ik/logika#1]
Got `TypeError` trying to run in both `xorg` and `wayland` modes.

```shell
$ python3 index.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/ig4er/Завантажене/index.py", line 7, in <module>
    box_Minutes(30)
TypeError: 'QSpinBox' object is not callable

$ export QT_QPA_PLATFORM=wayland

$ python3 index.py              
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/ig4er/Завантажене/index.py", line 7, in <module>
    box_Minutes(30)
TypeError: 'QSpinBox' object is not callable
```
Trying to comment the lines that causing this error isn't really helpful, because of `TypeError` in `RadioGroup.addButton(rbtn_1)` on line 16.
```shell
Traceback (most recent call last):
  File "/home/ig4er/Завантажене/index.py", line 16, in <module>
    RadioGroup.addButton(rbtn_1)
TypeError: addButton(self, a0: QAbstractButton, id: int = -1): first argument of unbound method must have type 'QButtonGroup'
```
Also, this `layout_res` on line 35 isn't really do anything useful, but causes an error.

---
PIP package versions:
```freeze
PyQt5==5.15.9
PyQt5-sip==12.12.2
```

**Comment by XSden4ik** [comment]
Код не дописаний тому помилки ;)
